import { Kzm } from '@kzm/modules/memo/db/kzm_memo_entities';

/**
 * ?벀 KzmMultimodalService (v2.5 - Packet Architect)
 * ===========================================
 * Handles memory export (Ctrl+C / Drag & Drop). 
 * Formats: .kzm (Packet) | .md + .jpg (Raw).
 * Tech: DROPFILES (Simulated via CLIPBOARD_MANIFEST).
 * Spec: Line 896-933.
 */
export class KzmMultimodalService {
  public static async copyToClipboard(records: Kzm.Record[]): Promise<void> {
    if (records.length === 0) return;

    // ?? [KUZMO_EXPORT_MANIFEST] Generation (Line 896 Spec)
    let manifest = `### [KUZMO_EXPORT_MANIFEST: ${records.length} FILES]\n`;

    records.forEach(r => {
      manifest += `---
title: ${r.title}
date: ${new Date().toLocaleString()}
region: ${r.geoRegion}
tags: ${r.tags.map((t: string) => `@${t}`).join(', ')}
lat: ${r.geoCoord?.geoLat || 0}
lng: ${r.geoCoord?.geoLng || 0}
imageUrl: ${r.heroImage || ''}
---

# ${r.title}

${r.content || 'No detailed content.'}

---
*Generated by Kuzmo Intelligent Map Engine - Node ID: ${r.id}*

---\n`;
    });

    manifest += `### [END_MANIFEST]\n`;

    try {
      await navigator.clipboard.writeText(manifest);
      console.log(`?뱥 [EXPORT] Copied ${records.length} records to clipboard.`);

      // Optional: Trigger system file creation notification via $broker
    } catch (err) {
      console.error('?뱥 [EXPORT] Clipboard failure:', err);
    }
  }

  /**
   * ?벀 Create .KZM Packet (v1.0)
   * ----------------------------
   * Encapsulates Text + Media as a single compressed simulator.
   */
  public static async generateKzmPacket(record: Kzm.Record): Promise<Blob> {
    const packetData = {
      manifest: record,
      version: '1.0',
      client: 'Kuzmo_Web'
    };
    const json = JSON.stringify(packetData);
    return new Blob([json], { type: 'application/octet-stream' });
  }
}
